parent=base
import=common/keycloak
styles=css/variphi.css
scripts=js/variphi.js js/branding.js
kcButtonClass=vp-btn
kcButtonPrimaryClass=vp-btn-primary
kcInputClass=vp-input
forgotPasswordApiUrl=http://localhost:4702/member/auth/forgot-password
